矩阵运算，例如执行乘法、加法和减法，是任何神经网络中信号传播的重要操作。通常在计算中需要随机矩阵、零矩阵、一矩阵或者单位矩阵。
本节将告诉你如何获得不同类型的矩阵，以及如何对它们进行不同的矩阵处理操作。

# 具体做法

开始一个交互式会话，以便得到计算结果

In [1]:
import tensorflow as tf

In [2]:
# 定义一个交互式会话
sess = tf.InteractiveSession()

In [3]:
# 定义一个 5X5 的单位矩阵（Identity matrix）
I_matrix = tf.eye(5)
print(I_matrix.eval())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
# 定义一个变量初始化 10 X 10 的单位矩阵
X = tf.Variable(tf.eye(10))
X.initializer.run() # 初始化变量
print(X.eval())

Instructions for updating:
Colocations handled automatically by placer.
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [5]:
# 创建一个 5 X 10 的矩阵 数值随机产生
A = tf.Variable(tf.random_normal([5,10]))
A.initializer.run()

In [6]:
# 两个矩阵相乘
product = tf.matmul(A,X)
print(product.eval())

[[-1.7562445  -1.2579206  -1.227558   -0.13973784 -1.3584545  -0.08482748
   0.96668136  1.0502264   0.6847732  -0.69717294]
 [ 0.59302044 -0.34977388  0.44148666 -0.03140887 -2.027126   -2.0703988
   1.0385708   0.74552906  0.85771763 -0.03630293]
 [-0.65610033 -1.0544987  -0.43789974  0.30394718  0.7904768   0.41085345
  -0.20027894  0.5341104   1.4523803   0.09469876]
 [-0.02923389 -0.33870056  0.01225267 -1.0145562  -0.42859137  2.4296627
   0.30368295 -0.43137777  0.73419815 -1.3190943 ]
 [ 1.6146436   0.49379188  0.5044419  -0.41588846 -0.7328848   0.23632082
   1.4541899  -0.39804518 -0.9542143   0.10574745]]


In [8]:
# 创建一个1和0的随机矩阵，大小为5x10
b = tf.Variable(tf.random_uniform([5,10],0,2,dtype=tf.int32))
b.initializer.run()
print(b.eval())
b_new = tf.cast(b,dtype=tf.float32) # 强制转换为float32数据类型
print(b_new.eval())

[[0 0 0 0 1 0 1 1 1 0]
 [1 0 1 0 0 0 1 1 1 0]
 [1 1 1 0 1 1 0 0 0 1]
 [0 1 1 0 0 0 1 0 1 1]
 [0 1 0 0 1 0 0 1 1 0]]
[[0. 0. 0. 0. 1. 0. 1. 1. 1. 0.]
 [1. 0. 1. 0. 0. 0. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 0. 1. 0. 1. 1.]
 [0. 1. 0. 0. 1. 0. 0. 1. 1. 0.]]


In [10]:
# 两个矩阵相加
t_sum = tf.add(product,b_new)
t_sub = product - b_new
print("A*X + b\n",t_sum.eval())
print("A*X - b\n",t_sub.eval())

A*X + b
 [[-1.7562445  -1.2579206  -1.227558   -0.13973784 -0.35845447 -0.08482748
   1.9666814   2.0502264   1.6847732  -0.69717294]
 [ 1.5930204  -0.34977388  1.4414866  -0.03140887 -2.027126   -2.0703988
   2.038571    1.745529    1.8577176  -0.03630293]
 [ 0.34389967 -0.05449867  0.5621003   0.30394718  1.7904768   1.4108534
  -0.20027894  0.5341104   1.4523803   1.0946988 ]
 [-0.02923389  0.66129947  1.0122527  -1.0145562  -0.42859137  2.4296627
   1.3036829  -0.43137777  1.7341981  -0.3190943 ]
 [ 1.6146436   1.4937918   0.5044419  -0.41588846  0.26711518  0.23632082
   1.4541899   0.6019548   0.04578573  0.10574745]]
A*X - b
 [[-1.7562445  -1.2579206  -1.227558   -0.13973784 -2.3584545  -0.08482748
  -0.03331864  0.05022645 -0.3152268  -0.69717294]
 [-0.40697956 -0.34977388 -0.55851334 -0.03140887 -2.027126   -2.0703988
   0.03857076 -0.25447094 -0.14228237 -0.03630293]
 [-1.6561003  -2.0544987  -1.4378997   0.30394718 -0.2095232  -0.58914655
  -0.20027894  0.5341104   1.4523803

一些其他有用的矩阵操作，如按元素相乘、乘以一个标量、按元素相除、按元素余数相除等，可以执行如下语句：

In [11]:
# 创建连个随机的矩阵
a = tf.Variable(tf.random_normal([4,5],stddev=2))
b = tf.Variable(tf.random_normal([4,5],stddev=2))

按元素相乘

In [12]:
A = a*b

乘以标量2(multiplication with a scalar 2)

In [13]:
B = tf.scalar_mul(2,A)

按元素相除

In [14]:
C = tf.div(a,b) # tf.div 返回的张量的类型与第一个参数类型一致。

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


按元素余数相除(按对应的位置的元素取余数)

In [16]:
D = tf.mod(a,b)

In [17]:
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    writer = tf.summary.FileWriter('graphs',sess.graph)
    a,b,A_R,B_R,C_R,D_R = sess.run([a,b,A,B,C,D])
    print("a\n",a,"b\n",b,"a*b\n",A_R,"\n2*a*b\n",B_R,"\na/b\n",C_R,"\na%b\n",D_R)

a
 [[ 2.109432    1.3351588   1.8523835   2.6198235  -0.00651391]
 [-3.3333428  -1.2926564   3.3819215   1.5765857   0.7135894 ]
 [ 0.65029776  2.1612089   2.35223    -0.40238333 -2.4578614 ]
 [ 2.6196957  -0.5007441  -2.7259188   0.47895917  1.5141615 ]] b
 [[ 1.1803955   0.8255128  -1.4970315   1.4534935   3.2534344 ]
 [-1.0104425   0.91055655  1.5027902   0.3139164   0.24620976]
 [-1.1611841  -1.124029   -1.6266465   1.0697817   1.368517  ]
 [-1.371579   -0.2056276   0.6372065  -1.8175641  -0.3399816 ]] a*b
 [[ 2.489964    1.1021907  -2.7730763   3.8078964  -0.02119259]
 [ 3.3681512  -1.1770368   5.082319    0.49491608  0.17569266]
 [-0.7551154  -2.4292614  -3.826247   -0.4304623  -3.3636253 ]
 [-3.5931196   0.10296681 -1.7369732  -0.870539   -0.514787  ]] 
2*a*b
 [[ 4.979928    2.2043815  -5.5461526   7.6157928  -0.04238518]
 [ 6.7363024  -2.3540735  10.164638    0.98983216  0.35138533]
 [-1.5102308  -4.858523   -7.652494   -0.8609246  -6.7272506 ]
 [-7.1862392   0.20593362 -3.4739

In [18]:
writer.close()

## 解读分析
所有加法、减、除、乘（按元素相乘）、取余等矩阵的算术运算都要求两个张量矩阵是相同的数据类型，否则就会产生错误。可以使用 tf.cast() 将张量从一种数据类型转换为另一种数据类型。

## 拓展阅读
如果在整数张量之间进行除法，最好使用 tf.truediv(a，b)，因为它首先将整数张量转换为浮点类，然后再执行按位相除。